site:
  title: Let's STEAM project documentation

  # the 404 page and sitemap files only get generated when the url property is set
  url: https://letssteam.github.io/hardware-documentation/
  start_page: hardware::index.adoc
content:
  sources:
  - url: https://github.com/letssteam/hardware.git
    branches: master
  - url: https://github.com/letssteam/hardware-requirements.git
    branches: master
  - url: https://github.com/letssteam/hardware-technical-specification.git
    branches: master
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./docs
