site:
  title: Let's STEAM project documentation

  # the 404 page and sitemap files only get generated when the url property is set
  url: https://letssteam.github.io/documentation-site/
  start_page: hardware::index.adoc
content:
  sources:
  - url: https://github.com/letssteam/hardware.git
    branches: master
ui:
  bundle:
    url: https://github.com/letssteam/documentation-site-ui/releases/download/v0.1/ui-bundle.zip 
    snapshot: true
output:
  dir: ./docs
